package main

import (
	"flag"
	"path"
	"text/template"

	"google.golang.org/protobuf/compiler/protogen"
)

var embedTemplate = `// Code generated by protoc-gen-twirp-swagger-embed. DO NOT EDIT.
// source: {{ .Source }}

package {{ .GoPackageName }}

import (
	_ "embed"
)

//go:embed {{ .SwaggerFileName }}
var SwaggerJSON []byte
`

func main() {
	var flags flag.FlagSet
	outputSuffix := flags.String("output_suffix", ".swagger.json", "")
	opts := protogen.Options{
		ParamFunc: flags.Set,
	}
	opts.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			tpl := template.Must(template.New("embed").Parse(embedTemplate))
			out := f.GeneratedFilenamePrefix + *outputSuffix + ".go"
			g := gen.NewGeneratedFile(out, f.GoImportPath)

			if err := tpl.Execute(g, struct {
				Source          string
				GoPackageName   string
				SwaggerFileName string
			}{
				Source:          f.Desc.Path(),
				GoPackageName:   string(f.GoPackageName),
				SwaggerFileName: path.Base(f.GeneratedFilenamePrefix + *outputSuffix),
			}); err != nil {
				return err
			}
		}
		return nil
	})
}
