apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: scylla-cloud-poc
build:
  artifacts:
    - image: localhost/sc-poc
      context: .
      docker:
        dockerfile: ./k8s/docker/base.Dockerfile
deploy:
  helm:
    releases:
      - name: api
        namespace: scylla-cloud
        createNamespace: true
        chartPath: ./k8s/helm
        artifactOverrides:
          image: localhost/sc-poc
        overrides:
          replicas: 1
      - name: book
        namespace: scylla-cloud
        chartPath: ./k8s/helm
        artifactOverrides:
          image: localhost/sc-poc
        overrides:
          replicas: 2
